### ISSUE TITLE
replacing volley with retrofit

### ISSUE THREAD

**Issue by tyadav4268** [tyadav4268/NewsApp#1]
currently volley library is being used to fetch the data from the API, need to replace it with the retrofit library.

**Comment by dolatapatryk** [comment]
I would like to do this issue :) I'm forking project right now so wait for PR :)

**Comment by dolatapatryk** [comment]
But could you change project and issue labels 'hactoberfest' -> 'hacktoberfest'

**Comment by dolatapatryk** [comment]
PR https://github.com/tyadav4268/NewsApp/pull/2

**Comment by tyadav4268** [comment]
> But could you change project and issue labels 'hactoberfest' -> 'hacktoberfest'

Done. Thank you!
